grep 'cls2_' *.list >>chinapred.list
grep 'cls3_' *.list >>chinapred.list
grep 'cls4_' *.list >>chinapred.list
grep 'cls7_' *.list >>chinapred.list
grep 'cls8_' *.list >>chinapred.list
grep 'cls9_' *.list >>chinapred.list
grep 'cls10_' *.list >>chinapred.list
grep 'cls11_' *.list >>chinapred.list
grep 'cls12_' *.list >>chinapred.list
grep 'cls13_' *.list >>chinapred.list
grep 'cls14_' *.list >>chinapred.list
grep 'cls15_' *.list >>chinapred.list
grep 'cls21_' *.list >>chinapred.list
grep 'cls22_' *.list >>chinapred.list
grep 'cls23_' *.list >>chinapred.list
grep 'cls24_' *.list >>chinapred.list
grep 'cls25_' *.list >>chinapred.list
grep 'cls26_' *.list >>chinapred.list
grep 'cls27_' *.list >>chinapred.list
grep 'cls28_' *.list >>chinapred.list
grep 'cls29_' *.list >>chinapred.list
grep 'cls30_' *.list >>chinapred.list
grep 'cls31_' *.list >>chinapred.list
grep 'cls32_' *.list >>chinapred.list
grep 'cls33_' *.list >>chinapred.list
grep 'cls34_' *.list >>chinapred.list
grep 'cls35_' *.list >>chinapred.list
grep 'cls36_' *.list >>chinapred.list
grep 'cls37_' *.list >>chinapred.list
grep 'cls38_' *.list >>chinapred.list
grep 'cls39_' *.list >>chinapred.list
grep 'cls40_' *.list >>chinapred.list
grep 'cls41_' *.list >>chinapred.list
grep 'cls44_' *.list >>chinapred.list
grep 'cls45_' *.list >>chinapred.list
grep 'cls46_' *.list >>chinapred.list
grep 'cls47_' *.list >>chinapred.list
grep 'cls50_' *.list >>chinapred.list
grep 'cls51_' *.list >>chinapred.list
grep 'cls52_' *.list >>chinapred.list
grep 'cls53_' *.list >>chinapred.list
grep 'cls58_' *.list >>chinapred.list
grep 'cls59_' *.list >>chinapred.list
grep 'cls61_' *.list >>chinapred.list
grep 'cls62_' *.list >>chinapred.list
grep 'cls63_' *.list >>chinapred.list
grep 'cls73_' *.list >>chinapred.list
grep 'cls77_' *.list >>chinapred.list
grep 'cls79_' *.list >>chinapred.list
grep 'cls83_' *.list >>chinapred.list
grep 'cls84_' *.list >>chinapred.list
grep 'cls86_' *.list >>chinapred.list
grep 'cls87_' *.list >>chinapred.list
grep 'cls89_' *.list >>chinapred.list
grep 'cls93_' *.list >>chinapred.list
grep 'cls94_' *.list >>chinapred.list
grep 'cls95_' *.list >>chinapred.list
grep 'cls96_' *.list >>chinapred.list
grep 'cls97_' *.list >>chinapred.list
grep 'cls101_' *.list >>chinapred.list
grep 'cls102_' *.list >>chinapred.list
grep 'cls105_' *.list >>chinapred.list
grep 'cls106_' *.list >>chinapred.list
grep 'cls107_' *.list >>chinapred.list
grep 'cls109_' *.list >>chinapred.list
grep 'cls110_' *.list >>chinapred.list
grep 'cls111_' *.list >>chinapred.list
grep 'cls113_' *.list >>chinapred.list
grep 'cls114_' *.list >>chinapred.list
grep 'cls115_' *.list >>chinapred.list
grep 'cls117_' *.list >>chinapred.list
grep 'cls118_' *.list >>chinapred.list
grep 'cls119_' *.list >>chinapred.list
grep 'cls120_' *.list >>chinapred.list
grep 'cls121_' *.list >>chinapred.list
grep 'cls122_' *.list >>chinapred.list
grep 'cls126_' *.list >>chinapred.list
grep 'cls127_' *.list >>chinapred.list
grep 'cls128_' *.list >>chinapred.list
grep 'cls129_' *.list >>chinapred.list
grep 'cls130_' *.list >>chinapred.list
grep 'cls131_' *.list >>chinapred.list
grep 'cls132_' *.list >>chinapred.list
grep 'cls133_' *.list >>chinapred.list
grep 'cls135_' *.list >>chinapred.list
grep 'cls136_' *.list >>chinapred.list
grep 'cls137_' *.list >>chinapred.list
grep 'cls138_' *.list >>chinapred.list
grep 'cls141_' *.list >>chinapred.list
grep 'cls144_' *.list >>chinapred.list
grep 'cls145_' *.list >>chinapred.list
grep 'cls146_' *.list >>chinapred.list
grep 'cls148_' *.list >>chinapred.list
grep 'cls149_' *.list >>chinapred.list
grep 'cls150_' *.list >>chinapred.list
grep 'cls151_' *.list >>chinapred.list
grep 'cls152_' *.list >>chinapred.list
grep 'cls154_' *.list >>chinapred.list
grep 'cls157_' *.list >>chinapred.list
grep 'cls162_' *.list >>chinapred.list
grep 'cls163_' *.list >>chinapred.list
grep 'cls164_' *.list >>chinapred.list
grep 'cls165_' *.list >>chinapred.list
grep 'cls166_' *.list >>chinapred.list
grep 'cls167_' *.list >>chinapred.list
grep 'cls168_' *.list >>chinapred.list
grep 'cls170_' *.list >>chinapred.list
grep 'cls173_' *.list >>chinapred.list
grep 'cls176_' *.list >>chinapred.list
grep 'cls177_' *.list >>chinapred.list
grep 'cls178_' *.list >>chinapred.list
grep 'cls179_' *.list >>chinapred.list
grep 'cls180_' *.list >>chinapred.list
grep 'cls182_' *.list >>chinapred.list
grep 'cls183_' *.list >>chinapred.list
grep 'cls185_' *.list >>chinapred.list
grep 'cls186_' *.list >>chinapred.list
grep 'cls187_' *.list >>chinapred.list
grep 'cls188_' *.list >>chinapred.list
grep 'cls189_' *.list >>chinapred.list
grep 'cls190_' *.list >>chinapred.list
grep 'cls192_' *.list >>chinapred.list
grep 'cls193_' *.list >>chinapred.list
grep 'cls195_' *.list >>chinapred.list
grep 'cls196_' *.list >>chinapred.list
